/**
 * Phase 13 investor target list (ELAH-FUND-LIST-001).
 * Public firms only. No emails. Fusion VC is seeded separately — skip here.
 * Do not mark contacted. Agents never send mail.
 */

export type Phase13InvestorSeed = {
  name: string;
  organization: string;
  role: string | null;
  contactType: "investor";
  email: null;
  linkedInUrl: string;
  sector: "Venture Capital";
  relevance: string;
  outreachStatus: "identified" | "research";
  priority: "high" | "medium" | "low";
  notes: string;
};

function note(opts: {
  wave: "1" | "2" | "park";
  thesis: string;
  source: string;
  partner: string;
}): string {
  return [
    `Wave ${opts.wave}.`,
    `Thesis: ${opts.thesis}.`,
    `Source: ${opts.source}.`,
    `Partner (published): ${opts.partner}.`,
    "Email: not on public page — do not invent.",
    "Agents never send mail.",
  ].join(" ");
}

/** Additional investor rows (excludes Fusion VC). */
export const PHASE13_INVESTORS: Phase13InvestorSeed[] = [
  {
    name: "Cyberstarts",
    organization: "Cyberstarts",
    role: "Gili Raanan, Founder",
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.cyberstarts.com/",
    sector: "Venture Capital",
    relevance: "Cyber-only Israeli seed firm; day-one partner for security companies.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "cybersecurity, seed, Israel",
      source: "https://www.cyberstarts.com/",
      partner: "Gili Raanan",
    }),
  },
  {
    name: "Glilot Capital",
    organization: "Glilot Capital",
    role: "Kobi Samboursky, Co-Founder & Managing Partner",
    contactType: "investor",
    email: null,
    linkedInUrl: "https://glilotcapital.com/",
    sector: "Venture Capital",
    relevance: "Israeli cyber + AI seed franchise (G-Seed) with enterprise security network.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "cybersecurity, AI, seed, enterprise, Israel",
      source: "https://glilotcapital.com/",
      partner: "Kobi Samboursky",
    }),
  },
  {
    name: "YL Ventures",
    organization: "YL Ventures",
    role: "Yoav Andrew Leitersdorf, Managing Partner",
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.ylventures.com/",
    sector: "Venture Capital",
    relevance: "Cyber-only seed-from-inception fund; Israel founders, US GTM.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "cybersecurity, seed, Israel + US",
      source: "https://www.ylventures.com/",
      partner: "Yoav Andrew Leitersdorf",
    }),
  },
  {
    name: "Hetz Ventures",
    organization: "Hetz Ventures",
    role: "Pavel Livshiz, General Partner",
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.hetz.vc/",
    sector: "Venture Capital",
    relevance: "Israeli seed fund with published cyber GP and AI/data thesis.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, AI, cybersecurity, data, Israel",
      source: "https://www.hetz.vc/",
      partner: "Pavel Livshiz",
    }),
  },
  {
    name: "lool ventures",
    organization: "lool ventures",
    role: "Avichay Nissenbaum, General Partner",
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.lool.vc/",
    sector: "Venture Capital",
    relevance: "Israel seed fund; public early-check posture across AI, fintech, cyber.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "pre-seed, seed, AI, fintech, cyber, Israel",
      source: "https://www.lool.vc/",
      partner: "Avichay Nissenbaum",
    }),
  },
  {
    name: "Entrée Capital",
    organization: "Entrée Capital",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.entreecap.com/",
    sector: "Venture Capital",
    relevance: "Early-stage software / fintech / AI with Israel + London + NY presence.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "pre-seed, seed, AI, fintech, cyber",
      source: "https://www.entreecap.com/",
      partner: "TBD",
    }),
  },
  {
    name: "TLV Partners",
    organization: "TLV Partners",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.tlv.partners",
    sector: "Venture Capital",
    relevance: "Tel Aviv seed firm covering cyber, data, AI, and fintech.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, AI, cybersecurity, fintech, Israel",
      source: "https://www.tlv.partners",
      partner: "TBD",
    }),
  },
  {
    name: "NFX",
    organization: "NFX",
    role: "Gigi Levy-Weiss",
    contactType: "investor",
    email: null,
    linkedInUrl: "https://nfx.com/",
    sector: "Venture Capital",
    relevance: "Seed firm with a large Israel practice and public AI / fintech writing.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, AI, fintech, Israel + US",
      source: "https://nfx.com/",
      partner: "Gigi Levy-Weiss",
    }),
  },
  {
    name: "Grove Ventures",
    organization: "Grove Ventures",
    role: "Dov Moran",
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.groveventures.com/",
    sector: "Venture Capital",
    relevance: "Israeli early-stage fund focused on enterprise AI and infrastructure.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "pre-seed, seed, enterprise AI, AI infra, Israel",
      source: "https://www.groveventures.com/",
      partner: "Dov Moran",
    }),
  },
  {
    name: "F2 Capital",
    organization: "F2 Capital",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.f2vc.com/",
    sector: "Venture Capital",
    relevance: "Public 0-to-1 Israel seed firm; cyber names on the firm site.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "early-stage, AI, cybersecurity, Israel",
      source: "https://www.f2vc.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Zeev Ventures",
    organization: "Zeev Ventures",
    role: "Oren Zeev",
    contactType: "investor",
    email: null,
    linkedInUrl: "https://zeevventures.com/",
    sector: "Venture Capital",
    relevance: "Seed investor with Israeli + US companies, including security names on the firm site.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, enterprise, fintech, cyber, Israel + US",
      source: "https://zeevventures.com/",
      partner: "Oren Zeev",
    }),
  },
  {
    name: "Pitango First",
    organization: "Pitango First",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.pitango.com/first/",
    sector: "Venture Capital",
    relevance: "Pitango’s public seed vehicle; cyber, gen-AI, and fintech coverage.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, cybersecurity, AI, fintech, Israel",
      source: "https://www.pitango.com/first/",
      partner: "TBD",
    }),
  },
  {
    name: "iAngels",
    organization: "iAngels",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.iangels.com/",
    sector: "Venture Capital",
    relevance: "Israel early-stage platform; local pre-seed/seed node, not a specialist cyber fund.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "pre-seed, seed, Israel",
      source: "https://www.iangels.com/",
      partner: "TBD",
    }),
  },
  {
    name: "First Round Capital",
    organization: "First Round Capital",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.firstround.com/",
    sector: "Venture Capital",
    relevance: "US seed firm with public enterprise / AI / fintech coverage.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, enterprise, AI, fintech, US",
      source: "https://www.firstround.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Point Nine",
    organization: "Point Nine",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.pointnine.com/",
    sector: "Venture Capital",
    relevance: "European early-stage B2B/AI firm; enterprise software thesis.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, B2B SaaS, AI, Europe",
      source: "https://www.pointnine.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Seedcamp",
    organization: "Seedcamp",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://seedcamp.com/",
    sector: "Venture Capital",
    relevance: "European seed platform covering AI, cyber, and fintech.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "pre-seed, seed, AI, cybersecurity, fintech, Europe",
      source: "https://seedcamp.com/",
      partner: "TBD",
    }),
  },
  {
    name: "QED Investors",
    organization: "QED Investors",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.qedinvestors.com/",
    sector: "Venture Capital",
    relevance: "Fintech-specialist firm; fit if framed as bank-risk infrastructure.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "fintech, US / global",
      source: "https://www.qedinvestors.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Nyca Partners",
    organization: "Nyca Partners",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.nyca.com/",
    sector: "Venture Capital",
    relevance: "Financial-services technology investor; thematic fit for bank buyers.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "fintech, seed, US",
      source: "https://www.nyca.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Ballistic Ventures",
    organization: "Ballistic Ventures",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.ballisticventures.com/",
    sector: "Venture Capital",
    relevance: "Cyber-only early-stage US firm; first-partner posture for security founders.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "cybersecurity, early-stage, US",
      source: "https://www.ballisticventures.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Unusual Ventures",
    organization: "Unusual Ventures",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.unusual.vc/",
    sector: "Venture Capital",
    relevance: "US enterprise-seed firm; company-building support for B2B security products.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, enterprise, US",
      source: "https://www.unusual.vc/",
      partner: "TBD",
    }),
  },
  {
    name: "Amplify Partners",
    organization: "Amplify Partners",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.amplifypartners.com/",
    sector: "Venture Capital",
    relevance: "Seed firm for technical infrastructure and AI; scoring-infra framing.",
    outreachStatus: "identified",
    priority: "high",
    notes: note({
      wave: "1",
      thesis: "seed, AI infrastructure, enterprise, US",
      source: "https://www.amplifypartners.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Aleph",
    organization: "Aleph",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.aleph.vc/",
    sector: "Venture Capital",
    relevance: "Premier Israeli firm; typically later than a first pre-seed check.",
    outreachStatus: "research",
    priority: "medium",
    notes: note({
      wave: "2",
      thesis: "later seed / Series A, Israel",
      source: "https://www.aleph.vc/",
      partner: "TBD",
    }),
  },
  {
    name: "Team8",
    organization: "Team8",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.team8.vc/",
    sector: "Venture Capital",
    relevance: "Cyber/fintech platform that builds and invests; often in-house creation.",
    outreachStatus: "research",
    priority: "medium",
    notes: note({
      wave: "2",
      thesis: "cybersecurity, fintech, company-builder, Israel",
      source: "https://www.team8.vc/",
      partner: "TBD",
    }),
  },
  {
    name: "Ten Eleven Ventures",
    organization: "Ten Eleven Ventures",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.1011vc.com/",
    sector: "Venture Capital",
    relevance: "Cyber-specialist, stage-agnostic; more natural after a seed lead.",
    outreachStatus: "research",
    priority: "medium",
    notes: note({
      wave: "2",
      thesis: "cybersecurity, multi-stage, US",
      source: "https://www.1011vc.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Paladin Capital Group",
    organization: "Paladin Capital Group",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.paladincapgroup.com/",
    sector: "Venture Capital",
    relevance: "Multi-stage cyber/AI investor; later-check profile.",
    outreachStatus: "research",
    priority: "medium",
    notes: note({
      wave: "2",
      thesis: "cybersecurity, AI, deep tech, multi-stage, US",
      source: "https://www.paladincapgroup.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Viola Ventures",
    organization: "Viola Ventures",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.viola-group.com/fund/violaventures/",
    sector: "Venture Capital",
    relevance: "Large Israeli early-stage franchise; often a follow-on or larger first check.",
    outreachStatus: "research",
    priority: "medium",
    notes: note({
      wave: "2",
      thesis: "seed through B, AI, fintech, enterprise, Israel",
      source: "https://www.viola-group.com/fund/violaventures/",
      partner: "TBD",
    }),
  },
  {
    name: "OurCrowd",
    organization: "OurCrowd",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.ourcrowd.com/",
    sector: "Venture Capital",
    relevance: "Parked: crowdfunding / platform model, not classic pre-seed partnership outbound.",
    outreachStatus: "research",
    priority: "low",
    notes: note({
      wave: "park",
      thesis: "crowdfunding / investment platform",
      source: "https://www.ourcrowd.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Vintage Investment Partners",
    organization: "Vintage Investment Partners",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.vintage-ip.com/",
    sector: "Venture Capital",
    relevance: "Parked: fund-of-funds / secondaries; not a direct seed lead.",
    outreachStatus: "research",
    priority: "low",
    notes: note({
      wave: "park",
      thesis: "fund-of-funds, secondaries",
      source: "https://www.vintage-ip.com/",
      partner: "TBD",
    }),
  },
  {
    name: "Y Combinator",
    organization: "Y Combinator",
    role: null,
    contactType: "investor",
    email: null,
    linkedInUrl: "https://www.ycombinator.com/",
    sector: "Venture Capital",
    relevance: "Parked: apply-only accelerator, not founder-CRM outbound email.",
    outreachStatus: "research",
    priority: "low",
    notes: note({
      wave: "park",
      thesis: "accelerator, apply-only",
      source: "https://www.ycombinator.com/",
      partner: "TBD",
    }),
  },
];

export function investorMatchKey(organization: string | null, name: string): string {
  return (organization || name).trim().toLowerCase();
}
