/**
 * Roadmap phase definitions — every task from the founder operating brief.
 * Status is assigned at seed time via evidence map in seed/index.ts.
 */
export interface PhaseSpec {
  phase: string;
  workstream: string;
  category: string;
  tasks: string[];
}

export const PHASE_SPECS: PhaseSpec[] = [
  {
    phase: "Phase 0 — Product definition and architecture",
    workstream: "Product",
    category: "Architecture",
    tasks: [
      "Finalize the exact ELAH banking MVP scope.",
      "Define the primary banking use cases.",
      "Define the event schema.",
      "Define the input contract for ELAH.",
      "Define the output contract for ELAH.",
      "Define the human-intention score semantics.",
      "Define confidence and uncertainty semantics.",
      "Define the coordinate system for the intention graph.",
      "Define explainability requirements.",
      "Define the boundary between ELAH and the bank's policy engine.",
      "Define the threshold configuration model.",
      "Define service-level requirements.",
      "Define latency targets.",
      "Define throughput targets.",
      "Define data-retention requirements.",
      "Define privacy requirements.",
      "Document the system architecture.",
      "Document the threat model.",
      "Document assumptions and non-goals.",
      "Decide which components belong in the current Next.js application.",
      "Decide which components belong in the separate ELAH service.",
      "Define the MVP success metrics.",
    ],
  },
  {
    phase: "Phase 1 — Banking simulator stabilization",
    workstream: "Engineering",
    category: "Simulator",
    tasks: [
      "Audit the existing banking simulator.",
      "Document all existing banking flows.",
      "Verify authentication and authorization behavior.",
      "Verify the simulated user and account database.",
      "Verify user tiers and permissions.",
      "Standardize banking action names.",
      "Add or validate login events.",
      "Add or validate logout events.",
      "Add or validate transfer events.",
      "Add or validate withdrawal events.",
      "Add or validate account-data download events.",
      "Add or validate profile-change events.",
      "Add or validate beneficiary-management events.",
      "Add or validate device-change events.",
      "Add or validate password-reset events.",
      "Add or validate high-risk banking actions.",
      "Ensure every action has a unique event ID.",
      "Ensure every action includes timestamps.",
      "Ensure events include user, session, device, source, and action context.",
      "Ensure agent-triggered actions can be distinguished from directly triggered actions.",
      "Add repeatable simulation scenarios.",
      "Add abnormal and suspicious user scenarios.",
      "Add legitimate edge-case scenarios.",
      "Create simulator reset functionality.",
      "Create simulator seed scripts.",
      "Validate that existing banking functionality remains intact.",
    ],
  },
  {
    phase: "Phase 2 — Agent observability and event collection",
    workstream: "Engineering",
    category: "Observability",
    tasks: [
      "Audit the integrated AI banking agent.",
      "Map all agent tools.",
      "Document all agent capabilities.",
      "Capture the original user request.",
      "Capture assistant messages.",
      "Capture model outputs.",
      "Capture tool-call requests.",
      "Capture tool-call arguments.",
      "Capture tool-call results.",
      "Capture the resulting banking action.",
      "Capture errors and retries.",
      "Capture session and conversation identifiers.",
      "Capture action chains.",
      "Create a normalized event envelope.",
      "Preserve ordering between events.",
      "Correlate user intent with agent execution.",
      "Add data-quality checks.",
      "Add missing-field alerts.",
      "Add duplicate-event detection.",
      "Add schema-version support.",
      "Ensure logs can be exported for training.",
      "Add a live event viewer.",
      "Add an event-detail view.",
      "Add filtering by user, session, action, tool, and result.",
    ],
  },
  {
    phase: "Phase 3 — ELAH service foundation",
    workstream: "Engineering",
    category: "Backend",
    tasks: [
      "Create the separate ELAH service.",
      "Choose and document the service language and framework.",
      "Define the scoring API.",
      "Add health-check endpoints.",
      "Add versioning.",
      "Add authentication between the banking application and ELAH.",
      "Add input validation.",
      "Add structured error responses.",
      "Add request logging.",
      "Add tracing and correlation IDs.",
      "Add latency measurements.",
      "Add local development configuration.",
      "Add test configuration.",
      "Add production configuration.",
      "Add Docker support if appropriate.",
      "Add CI checks.",
      "Add unit tests.",
      "Add integration tests.",
      "Add API contract tests.",
      "Create a mock scoring implementation.",
      "Connect the existing banking simulator to the mock ELAH service.",
      "Store ELAH responses alongside events.",
      "Handle ELAH service timeouts safely.",
      "Define fallback behavior.",
      "Ensure ELAH cannot directly execute banking actions.",
    ],
  },
  {
    phase: "Phase 4 — Dataset and labeling system",
    workstream: "Data",
    category: "Dataset",
    tasks: [
      "Define the training-data schema.",
      "Define the evaluation-data schema.",
      "Define the label taxonomy.",
      "Define human-intention dimensions.",
      "Define malicious-intent dimensions.",
      "Define accidental-error dimensions.",
      "Define ambiguity labels.",
      "Define confidence labels.",
      "Define contextual-risk labels.",
      "Create a scenario-template format.",
      "Convert existing simulator logs into the normalized schema.",
      "Clean existing logs.",
      "Remove duplicate records.",
      "Validate timestamps and ordering.",
      "Detect incomplete examples.",
      "Create synthetic legitimate banking scenarios.",
      "Create synthetic suspicious banking scenarios.",
      "Create synthetic malicious banking scenarios.",
      "Create synthetic ambiguous scenarios.",
      "Create multi-step agent scenarios.",
      "Create prompt-injection scenarios.",
      "Create indirect prompt-injection scenarios.",
      "Create compromised-tool scenarios.",
      "Create excessive-permission scenarios.",
      "Create mistaken-user scenarios.",
      "Create conflicting-instruction scenarios.",
      "Create authorization-boundary scenarios.",
      "Create data-exfiltration scenarios.",
      "Create high-value transfer scenarios.",
      "Create unusual-device scenarios.",
      "Create unusual-location scenarios.",
      "Create behavior-drift scenarios.",
      "Create a manual labeling interface.",
      "Add reviewer notes.",
      "Add labeling guidelines.",
      "Add inter-reviewer agreement tracking.",
      "Add dataset versioning.",
      "Split data into training, validation, and holdout test sets.",
      "Prevent scenario leakage between splits.",
      "Track data provenance.",
      "Review privacy and anonymization requirements.",
    ],
  },
  {
    phase: "Phase 5 — Baseline scoring system",
    workstream: "Model",
    category: "Baseline",
    tasks: [
      "Build a deterministic rules-based baseline.",
      "Define baseline risk features.",
      "Define behavioral features.",
      "Define agent-behavior features.",
      "Define banking-context features.",
      "Define action-chain features.",
      "Implement feature extraction.",
      "Produce a baseline human-intention score.",
      "Produce baseline coordinates.",
      "Produce baseline explanations.",
      "Add reason codes.",
      "Add uncertainty handling.",
      "Add score normalization.",
      "Add test fixtures.",
      "Evaluate the baseline against labeled scenarios.",
      "Measure false positives.",
      "Measure false negatives.",
      "Measure precision and recall.",
      "Measure calibration.",
      "Measure latency.",
      "Document baseline limitations.",
      "Display baseline outputs in the dashboard.",
    ],
  },
  {
    phase: "Phase 6 — ELAH model development",
    workstream: "Model",
    category: "ML",
    tasks: [
      "Define the initial model architecture.",
      "Compare rules, classical machine learning, small language models, and hybrid approaches.",
      "Establish a simple baseline model.",
      "Build the training pipeline.",
      "Build the evaluation pipeline.",
      "Implement feature preprocessing.",
      "Implement model versioning.",
      "Implement experiment tracking.",
      "Train on simulator data.",
      "Train on synthetic data.",
      "Evaluate on a protected holdout set.",
      "Perform error analysis.",
      "Analyze errors by banking action.",
      "Analyze errors by user-intent category.",
      "Analyze errors by agent/tool behavior.",
      "Analyze model confidence.",
      "Calibrate output probabilities.",
      "Compare multiple calibration methods.",
      "Define abstention behavior for uncertain cases.",
      "Test robustness to missing context.",
      "Test robustness to noisy context.",
      "Test robustness to adversarial inputs.",
      "Test inference speed.",
      "Test throughput.",
      "Test model size.",
      "Evaluate whether the model is lightweight enough.",
      "Create model cards.",
      "Document dataset versions used.",
      "Document known limitations.",
      "Add rollback support between model versions.",
      "Integrate the best model into the ELAH service.",
    ],
  },
  {
    phase: "Phase 7 — Explainability and intention graph",
    workstream: "Model",
    category: "Explainability",
    tasks: [
      "Finalize the dimensions of the intention graph.",
      "Define the meaning of each axis.",
      "Define coordinate calculation.",
      "Define how action sequences appear on the graph.",
      "Define how confidence appears visually.",
      "Define how uncertainty appears visually.",
      "Define how risk appears visually.",
      "Create a three-layer intention visualization.",
      "Display individual action points.",
      "Display action trajectories.",
      "Display user-request-to-agent-action relationships.",
      "Display deviations from expected behavior.",
      "Display model evidence.",
      "Display contributing factors.",
      "Display reason codes.",
      "Display alternative interpretations.",
      "Add an event explanation panel.",
      "Add model-version information.",
      "Add raw-event inspection for authorized users.",
      "Test whether explanations are understandable to banking analysts.",
      "Test whether explanations remain faithful to model behavior.",
      "Avoid exposing private model reasoning or unsupported chain-of-thought.",
      "Use concise evidence-based explanations instead.",
    ],
  },
  {
    phase: "Phase 8 — Security architecture and red teaming",
    workstream: "Security",
    category: "Security",
    tasks: [
      "Complete the ELAH threat model.",
      "Identify ELAH trust boundaries.",
      "Protect the scoring service from prompt injection.",
      "Protect the scoring service from malicious event content.",
      "Prevent the monitored agent from controlling the evaluator.",
      "Isolate evaluation components where appropriate.",
      "Validate all incoming data.",
      "Limit tool and network permissions.",
      "Add rate limiting.",
      "Add authentication and authorization.",
      "Add secrets management.",
      "Add audit logging.",
      "Add tamper-evident event handling where practical.",
      "Test replay attacks.",
      "Test event manipulation.",
      "Test missing-event attacks.",
      "Test reordered-event attacks.",
      "Test evaluator poisoning.",
      "Test training-data poisoning.",
      "Test prompt injection through tool outputs.",
      "Test indirect prompt injection.",
      "Test malicious user instructions.",
      "Test compromised agent behavior.",
      "Test compromised tool behavior.",
      "Test excessive autonomy.",
      "Test logical drift caused by model mistakes.",
      "Test attacks against the ELAH evaluator itself.",
      "Create red-team scenarios.",
      "Record findings and remediation tasks.",
      "Define severity levels.",
      "Define security acceptance criteria for the MVP.",
      "Conduct an external security review when ready.",
    ],
  },
  {
    phase: "Phase 9 — Product dashboard and analyst experience",
    workstream: "Dashboard",
    category: "Product",
    tasks: [
      "Build the ELAH operational dashboard.",
      "Add real-time or near-real-time updates.",
      "Add event list.",
      "Add event details.",
      "Add score visualization.",
      "Add confidence visualization.",
      "Add intention coordinates.",
      "Add action-chain visualization.",
      "Add explanation panel.",
      "Add risk indicators.",
      "Add filtering.",
      "Add search.",
      "Add date ranges.",
      "Add user and session filters.",
      "Add banking-action filters.",
      "Add agent/tool filters.",
      "Add model-version filters.",
      "Add threshold visualization.",
      "Let the customer configure thresholds without changing the ELAH score.",
      "Add saved views.",
      "Add analyst notes.",
      "Add review status.",
      "Add false-positive marking.",
      "Add false-negative marking.",
      "Add feedback collection.",
      "Add export functionality.",
      "Add CSV or JSON export.",
      "Add role-based access.",
      "Add audit history.",
      "Add loading, empty, and error states.",
      "Verify mobile and desktop responsiveness.",
      "Run accessibility checks.",
    ],
  },
  {
    phase: "Phase 10 — Evaluation and MVP readiness",
    workstream: "Product",
    category: "Evaluation",
    tasks: [
      "Define the golden evaluation set.",
      "Define minimum acceptable accuracy.",
      "Define minimum acceptable calibration.",
      "Define acceptable false-positive rates.",
      "Define acceptable false-negative rates.",
      "Define acceptable latency.",
      "Define acceptable availability.",
      "Define explainability acceptance criteria.",
      "Define banking-analyst usability criteria.",
      "Run end-to-end tests.",
      "Run load tests.",
      "Run failure-mode tests.",
      "Run security tests.",
      "Run data-loss tests.",
      "Run service-timeout tests.",
      "Run model-rollback tests.",
      "Validate monitoring and alerting.",
      "Validate dashboard correctness.",
      "Validate score consistency.",
      "Validate threshold separation.",
      "Document release procedures.",
      "Document incident procedures.",
      "Document known limitations.",
      "Prepare the MVP demo.",
      "Create repeatable demo scenarios.",
      "Create a technical demo script.",
      "Create a non-technical demo script.",
      "Produce an MVP readiness report.",
    ],
  },
  {
    phase: "Phase 11 — User discovery and customer validation",
    workstream: "Business",
    category: "Validation",
    tasks: [
      "Define the ideal banking customer profile.",
      "Identify relevant roles inside banks.",
      "Identify fraud leaders.",
      "Identify cybersecurity leaders.",
      "Identify AI governance leaders.",
      "Identify digital-banking leaders.",
      "Identify innovation leaders.",
      "Identify risk and compliance stakeholders.",
      "Build a list of banks and fintech companies.",
      "Prioritize Israeli banks.",
      "Prioritize fintech design partners.",
      "Create an interview script.",
      "Conduct banking-domain interviews.",
      "Conduct security-team interviews.",
      "Conduct AI-governance interviews.",
      "Document current workflows.",
      "Document existing agent-security concerns.",
      "Validate whether human-intention scoring is valuable.",
      "Validate which explanations customers need.",
      "Validate acceptable false-positive rates.",
      "Validate deployment constraints.",
      "Validate on-premise or private-cloud needs.",
      "Validate data-residency requirements.",
      "Validate procurement constraints.",
      "Validate regulatory concerns.",
      "Record interview notes.",
      "Convert insights into product tasks.",
      "Track repeated pain points.",
      "Define pilot qualification criteria.",
    ],
  },
  {
    phase: "Phase 12 — Pilot acquisition",
    workstream: "Business",
    category: "Pilot",
    tasks: [
      "Define the pilot offer.",
      "Define pilot scope.",
      "Define pilot duration.",
      "Define pilot success metrics.",
      "Define technical integration requirements.",
      "Define customer responsibilities.",
      "Define ELAH responsibilities.",
      "Create a pilot one-pager.",
      "Create a pilot presentation.",
      "Create a product demo.",
      "Create an architecture overview.",
      "Create a security overview.",
      "Create an FAQ.",
      "Create a data-processing explanation.",
      "Create an initial pilot agreement checklist.",
      "Identify pilot candidates.",
      "Contact potential design partners.",
      "Schedule discovery meetings.",
      "Run technical workshops.",
      "Collect integration requirements.",
      "Create a pilot implementation plan.",
      "Select the first pilot partner.",
      "Prepare a sandbox integration.",
      "Execute the pilot.",
      "Collect analyst feedback.",
      "Measure pilot outcomes.",
      "Produce a pilot report.",
      "Obtain a testimonial or reference when appropriate.",
    ],
  },
  {
    phase: "Phase 13 — Fundraising and investor outreach",
    workstream: "Business",
    category: "Fundraising",
    tasks: [
      "Define the fundraising target.",
      "Define the expected runway.",
      "Build the financial plan.",
      "Define use of funds.",
      "Define hiring priorities.",
      "Build the investor target list.",
      "Prioritize pre-seed and seed funds.",
      "Prioritize AI, cybersecurity, fintech, and enterprise investors.",
      "Identify relevant partners at each fund.",
      "Track investor emails and LinkedIn profiles.",
      "Draft a short cold email.",
      "Draft personalized outreach variants.",
      "Create the investor deck.",
      "Create a concise one-pager.",
      "Create a technical appendix.",
      "Create a product demo.",
      "Create a data room.",
      "Add company documents.",
      "Add architecture documents.",
      "Add roadmap documents.",
      "Add market research.",
      "Add financial assumptions.",
      "Add cap-table information when available.",
      "Contact investors.",
      "Track replies.",
      "Schedule meetings.",
      "Track investor questions.",
      "Track follow-ups.",
      "Track introductions.",
      "Track passed investors and reasons.",
      "Refine the pitch based on feedback.",
      "Maintain an investor pipeline.",
    ],
  },
  {
    phase: "Phase 14 — Company, legal, privacy, and compliance",
    workstream: "Legal",
    category: "Compliance",
    tasks: [
      "Confirm the company structure for ELAH.",
      "Review founder and intellectual-property ownership.",
      "Prepare advisor or contractor agreements where required.",
      "Review open-source licenses.",
      "Create a privacy policy.",
      "Create terms for demo users.",
      "Define data-processing roles.",
      "Define data-retention policies.",
      "Define deletion procedures.",
      "Define access-control policies.",
      "Define incident-response procedures.",
      "Map relevant banking and privacy obligations.",
      "Review Israeli privacy requirements.",
      "Review GDPR relevance.",
      "Review financial-sector security expectations.",
      "Review AI governance requirements.",
      "Prepare a security questionnaire response library.",
      "Prepare an initial data-processing agreement checklist.",
      "Identify where professional legal advice is required.",
      "Do not present generated content as final legal advice.",
    ],
  },
  {
    phase: "Phase 15 — Team and operations",
    workstream: "Operations",
    category: "Operations",
    tasks: [
      "Define required founding-team roles.",
      "Define technical skill gaps.",
      "Define machine-learning skill gaps.",
      "Define security-research skill gaps.",
      "Define banking-domain skill gaps.",
      "Decide whether a technical co-founder is required.",
      "Identify potential advisors.",
      "Identify potential security researchers.",
      "Identify potential banking advisors.",
      "Define hiring order.",
      "Define contractor needs.",
      "Define equity and compensation questions for professional review.",
      "Set a weekly operating review.",
      "Set monthly milestone reviews.",
      "Maintain an issue and decision log.",
      "Maintain documentation.",
      "Define development standards.",
      "Define code-review standards.",
      "Define testing standards.",
      "Define release standards.",
      "Track infrastructure costs.",
      "Track model-training costs.",
      "Track monthly burn.",
      "Track runway.",
    ],
  },
];

export const MILESTONE_SPECS = [
  {
    order: 1,
    title: "Product and architecture definition complete",
    exitCriteria:
      "Event schema, scoring contract, architecture docs, and MVP scope signed off.",
    targetMonthsFromNow: 1,
  },
  {
    order: 2,
    title: "Banking simulator event coverage complete",
    exitCriteria: "All banking actions emit normalized events with full context.",
    targetMonthsFromNow: 2,
  },
  {
    order: 3,
    title: "End-to-end event collection operational",
    exitCriteria: "User request → agent → tool → banking action fully correlated.",
    targetMonthsFromNow: 2,
  },
  {
    order: 4,
    title: "Mock ELAH scoring service integrated",
    exitCriteria: "Banking app calls mock API and stores responses per event.",
    targetMonthsFromNow: 3,
  },
  {
    order: 5,
    title: "Version-one labeled dataset ready",
    exitCriteria: "≥200 labeled scenarios with train/val/test split and guidelines.",
    targetMonthsFromNow: 4,
  },
  {
    order: 6,
    title: "Rules-based baseline evaluated",
    exitCriteria: "Baseline metrics documented on golden evaluation set.",
    targetMonthsFromNow: 4,
  },
  {
    order: 7,
    title: "First trained ELAH model evaluated",
    exitCriteria: "Model beats baseline on holdout with documented error analysis.",
    targetMonthsFromNow: 6,
  },
  {
    order: 8,
    title: "Intention graph and explanations operational",
    exitCriteria: "Analysts can inspect coordinates and evidence per event.",
    targetMonthsFromNow: 6,
  },
  {
    order: 9,
    title: "Security and red-team baseline complete",
    exitCriteria: "Threat model, red-team scenarios, and remediations tracked.",
    targetMonthsFromNow: 5,
  },
  {
    order: 10,
    title: "Internal banking MVP ready",
    exitCriteria: "End-to-end demo with scoring, dashboard, and documentation.",
    targetMonthsFromNow: 7,
  },
  {
    order: 11,
    title: "Banking expert validation complete",
    exitCriteria: "≥5 expert interviews with documented insights and task updates.",
    targetMonthsFromNow: 5,
  },
  {
    order: 12,
    title: "First design partner identified",
    exitCriteria: "Named partner in pilot discussion stage with documented fit.",
    targetMonthsFromNow: 6,
  },
  {
    order: 13,
    title: "First pilot agreed",
    exitCriteria: "Signed pilot scope, success metrics, and integration plan.",
    targetMonthsFromNow: 8,
  },
  {
    order: 14,
    title: "First pilot launched",
    exitCriteria: "Partner sandbox integration live with analyst feedback loop.",
    targetMonthsFromNow: 9,
  },
  {
    order: 15,
    title: "Investor materials ready",
    exitCriteria: "Deck, one-pager, demo, and data room draft complete.",
    targetMonthsFromNow: 5,
  },
  {
    order: 16,
    title: "Initial fundraising outreach launched",
    exitCriteria: "Target list prioritized; first wave of outreach sent.",
    targetMonthsFromNow: 6,
  },
] as const;
